<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ZfPhpcrOdm\SessionFactory'                       => __DIR__ . '/src/ZfPhpcrOdm/SessionFactory.php',
    'ZfPhpcrOdm\ODM\PHPCR\Mapping\Driver\DriverChain' => __DIR__ . '/src/ZfPhpcrOdm/ODM/PHPCR/Mapping/Driver/DriverChain.php',
    'ZfPhpcrOdm\Version'                              => __DIR__ . '/src/ZfPhpcrOdm/Version.php',
    'ZfPhpcrOdm\Module'                               => __DIR__ . '/Module.php',
);